spring.application.name=ms-paciente

server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_db
spring.datasource.username=postgres
spring.datasource.password=M1yamoto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Documentação
springdoc.swagger-ui.path=/swagger-ui.html

# Feign Config (para se conectar a outros microsserviços)
spring.cloud.openfeign.client.config.default.connect-timeout=5000